### ISSUE TITLE
building error Math/Transform.h: No such file or directory

### ISSUE THREAD

**Issue by fjallraven** [Autodesk/LiveLink#15]
Get this error when building the maya plugin:  (2.1.0 Release for UE 5.1 only)
`MStreamedEntity.h:25:28: fatal error: Math/Transform.h: No such file or directory`
`MayaUnrealLiveLinkUtils.h:25:28: fatal error: Misc/FrameRate.h: No such file or directory`

I cannot seem to locate these headers in the repo, unreal, maya sdk.

Thank you

**Comment by boudrey** [comment]
Those are core headers that are available in the Engine.
Engine\Source\Runtime\Core\Public\Math\Transform.h
Engine\Source\Runtime\Core\Public\Misc\FrameRate.h

You can try those replacements but it might fail later if the compiler can't find those files.

#include "Math/Transform.h" -> #include "CoreMinimal.h"
#include "Misc/FrameRate.h" -> struct FFrameRate; 
#include "Misc/QualifiedFrameTime.h" -> struct FQualifiedFrameTime;
